In [1]:
import pandas as pd

df = pd.read_csv (r'mnist/mnist_test.csv')
print (df)

      0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  ...  0.659  0.660  \
0     0    0    0    0    0    0    0    0    0    0  ...      0      0
1     0    0    0    0    0    0    0    0    0    0  ...      0      0
2     0    0    0    0    0    0    0    0    0    0  ...      0      0
3     0    0    0    0    0    0    0    0    0    0  ...      0      0
4     0    0    0    0    0    0    0    0    0    0  ...      0      0
...  ..  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...
9994  0    0    0    0    0    0    0    0    0    0  ...      0      0
9995  0    0    0    0    0    0    0    0    0    0  ...      0      0
9996  0    0    0    0    0    0    0    0    0    0  ...      0      0
9997  0    0    0    0    0    0    0    0    0    0  ...      0      0
9998  0    0    0    0    0    0    0    0    0    0  ...      0      0

      0.661  0.662  0.663  0.664  0.665  0.666  0.667  7
0         0      0      0      0      0      0      0  2
1         0      0      0      0      0      0      0  1
2         0      0      0      0      0      0      0  0
3         0      0      0      0      0      0      0  4
4         0      0      0      0      0      0      0  1
...     ...    ...    ...    ...    ...    ...    ... ..
9994      0      0      0      0      0      0      0  2
9995      0      0      0      0      0      0      0  3
9996      0      0      0      0      0      0      0  4
9997      0      0      0      0      0      0      0  5
9998      0      0      0      0      0      0      0  6

[9999 rows x 785 columns]

In [2]:
labels = df.iloc[: , -1]
labels.nunique()

10

In [3]:
for i in range(0,len(labels)):
    if labels[i] != 0:
        labels[i] = 1

In [4]:
labels.nunique()

2

In [5]:
df.iloc[: , -1] = labels

In [6]:
df

,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,...,0.659,0.660,0.661,0.662,0.663,0.664,0.665,0.666,0.667,7
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9994,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
9995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
9996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
9997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
9998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [7]:
df.to_csv('binary_mnist/mnist_test.csv', index=False)

In [10]:
df = pd.read_csv (r'mnist/mnist_train.csv')
df.head(10)

,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,...,0.609,0.610,0.611,0.612,0.613,0.614,0.615,0.616,0.617,5
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,4
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,9
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,3
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,4
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,3

In [11]:
labels = df.iloc[: , -1]
labels.nunique()

10

In [12]:
for i in range(0,len(labels)):
    if labels[i] != 0:
        labels[i] = 1

In [13]:
df.to_csv('binary_mnist/mnist_train.csv', index=False)